/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HrisRouteImport } from './routes/hris'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserManagementUsersRouteImport } from './routes/user-management/users'
import { Route as UserManagementRolesRouteImport } from './routes/user-management/roles'
import { Route as UserManagementAccountRouteImport } from './routes/user-management/account'
import { Route as HrisTrainingRouteImport } from './routes/hris/training'
import { Route as HrisTimesheetsRouteImport } from './routes/hris/timesheets'
import { Route as HrisTimeManagementRouteImport } from './routes/hris/time-management'
import { Route as HrisSettingsRouteImport } from './routes/hris/settings'
import { Route as HrisReportsRouteImport } from './routes/hris/reports'
import { Route as HrisRecruitmentRouteImport } from './routes/hris/recruitment'
import { Route as HrisPerformanceRouteImport } from './routes/hris/performance'
import { Route as HrisOvertimeLogsRouteImport } from './routes/hris/overtime-logs'
import { Route as HrisOvertimeApprovalsRouteImport } from './routes/hris/overtime-approvals'
import { Route as HrisLeavesRouteImport } from './routes/hris/leaves'
import { Route as HrisHolidaysRouteImport } from './routes/hris/holidays'
import { Route as HrisEventsMeetingsRouteImport } from './routes/hris/events-meetings'
import { Route as HrisEmployeesRouteImport } from './routes/hris/employees'
import { Route as HrisDisciplinaryRouteImport } from './routes/hris/disciplinary'
import { Route as HrisDashboardRouteImport } from './routes/hris/dashboard'
import { Route as HrisCoreHrRouteImport } from './routes/hris/core-hr'
import { Route as HrisComplianceRouteImport } from './routes/hris/compliance'
import { Route as HrisCompensationRouteImport } from './routes/hris/compensation'
import { Route as HrisAttendanceRouteImport } from './routes/hris/attendance'
import { Route as DashboardModuleRouteImport } from './routes/dashboard.$module'
import { Route as HrisPayrollIndexRouteImport } from './routes/hris/payroll/index'
import { Route as HrisPayrollSalaryComponentsRouteImport } from './routes/hris/payroll/salary-components'
import { Route as HrisPayrollPeriodsRouteImport } from './routes/hris/payroll/periods'
import { Route as HrisPayrollDeductionsRouteImport } from './routes/hris/payroll/deductions'
import { Route as HrisEmployeesIdRouteImport } from './routes/hris/employees.$id'
import { Route as HrisPayrollRunsIdRouteImport } from './routes/hris/payroll/runs.$id'
import { Route as HrisPayrollEntriesIdRouteImport } from './routes/hris/payroll/entries.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HrisRoute = HrisRouteImport.update({
  id: '/hris',
  path: '/hris',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementUsersRoute = UserManagementUsersRouteImport.update({
  id: '/user-management/users',
  path: '/user-management/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRolesRoute = UserManagementRolesRouteImport.update({
  id: '/user-management/roles',
  path: '/user-management/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementAccountRoute = UserManagementAccountRouteImport.update({
  id: '/user-management/account',
  path: '/user-management/account',
  getParentRoute: () => rootRouteImport,
} as any)
const HrisTrainingRoute = HrisTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => HrisRoute,
} as any)
const HrisTimesheetsRoute = HrisTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => HrisRoute,
} as any)
const HrisTimeManagementRoute = HrisTimeManagementRouteImport.update({
  id: '/time-management',
  path: '/time-management',
  getParentRoute: () => HrisRoute,
} as any)
const HrisSettingsRoute = HrisSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HrisRoute,
} as any)
const HrisReportsRoute = HrisReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HrisRoute,
} as any)
const HrisRecruitmentRoute = HrisRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => HrisRoute,
} as any)
const HrisPerformanceRoute = HrisPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => HrisRoute,
} as any)
const HrisOvertimeLogsRoute = HrisOvertimeLogsRouteImport.update({
  id: '/overtime-logs',
  path: '/overtime-logs',
  getParentRoute: () => HrisRoute,
} as any)
const HrisOvertimeApprovalsRoute = HrisOvertimeApprovalsRouteImport.update({
  id: '/overtime-approvals',
  path: '/overtime-approvals',
  getParentRoute: () => HrisRoute,
} as any)
const HrisLeavesRoute = HrisLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => HrisRoute,
} as any)
const HrisHolidaysRoute = HrisHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => HrisRoute,
} as any)
const HrisEventsMeetingsRoute = HrisEventsMeetingsRouteImport.update({
  id: '/events-meetings',
  path: '/events-meetings',
  getParentRoute: () => HrisRoute,
} as any)
const HrisEmployeesRoute = HrisEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => HrisRoute,
} as any)
const HrisDisciplinaryRoute = HrisDisciplinaryRouteImport.update({
  id: '/disciplinary',
  path: '/disciplinary',
  getParentRoute: () => HrisRoute,
} as any)
const HrisDashboardRoute = HrisDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HrisRoute,
} as any)
const HrisCoreHrRoute = HrisCoreHrRouteImport.update({
  id: '/core-hr',
  path: '/core-hr',
  getParentRoute: () => HrisRoute,
} as any)
const HrisComplianceRoute = HrisComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => HrisRoute,
} as any)
const HrisCompensationRoute = HrisCompensationRouteImport.update({
  id: '/compensation',
  path: '/compensation',
  getParentRoute: () => HrisRoute,
} as any)
const HrisAttendanceRoute = HrisAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => HrisRoute,
} as any)
const DashboardModuleRoute = DashboardModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => DashboardRoute,
} as any)
const HrisPayrollIndexRoute = HrisPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => HrisRoute,
} as any)
const HrisPayrollSalaryComponentsRoute =
  HrisPayrollSalaryComponentsRouteImport.update({
    id: '/payroll/salary-components',
    path: '/payroll/salary-components',
    getParentRoute: () => HrisRoute,
  } as any)
const HrisPayrollPeriodsRoute = HrisPayrollPeriodsRouteImport.update({
  id: '/payroll/periods',
  path: '/payroll/periods',
  getParentRoute: () => HrisRoute,
} as any)
const HrisPayrollDeductionsRoute = HrisPayrollDeductionsRouteImport.update({
  id: '/payroll/deductions',
  path: '/payroll/deductions',
  getParentRoute: () => HrisRoute,
} as any)
const HrisEmployeesIdRoute = HrisEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HrisEmployeesRoute,
} as any)
const HrisPayrollRunsIdRoute = HrisPayrollRunsIdRouteImport.update({
  id: '/payroll/runs/$id',
  path: '/payroll/runs/$id',
  getParentRoute: () => HrisRoute,
} as any)
const HrisPayrollEntriesIdRoute = HrisPayrollEntriesIdRouteImport.update({
  id: '/payroll/entries/$id',
  path: '/payroll/entries/$id',
  getParentRoute: () => HrisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRouteWithChildren
  '/hris': typeof HrisRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/dashboard/$module': typeof DashboardModuleRoute
  '/hris/attendance': typeof HrisAttendanceRoute
  '/hris/compensation': typeof HrisCompensationRoute
  '/hris/compliance': typeof HrisComplianceRoute
  '/hris/core-hr': typeof HrisCoreHrRoute
  '/hris/dashboard': typeof HrisDashboardRoute
  '/hris/disciplinary': typeof HrisDisciplinaryRoute
  '/hris/employees': typeof HrisEmployeesRouteWithChildren
  '/hris/events-meetings': typeof HrisEventsMeetingsRoute
  '/hris/holidays': typeof HrisHolidaysRoute
  '/hris/leaves': typeof HrisLeavesRoute
  '/hris/overtime-approvals': typeof HrisOvertimeApprovalsRoute
  '/hris/overtime-logs': typeof HrisOvertimeLogsRoute
  '/hris/performance': typeof HrisPerformanceRoute
  '/hris/recruitment': typeof HrisRecruitmentRoute
  '/hris/reports': typeof HrisReportsRoute
  '/hris/settings': typeof HrisSettingsRoute
  '/hris/time-management': typeof HrisTimeManagementRoute
  '/hris/timesheets': typeof HrisTimesheetsRoute
  '/hris/training': typeof HrisTrainingRoute
  '/user-management/account': typeof UserManagementAccountRoute
  '/user-management/roles': typeof UserManagementRolesRoute
  '/user-management/users': typeof UserManagementUsersRoute
  '/hris/employees/$id': typeof HrisEmployeesIdRoute
  '/hris/payroll/deductions': typeof HrisPayrollDeductionsRoute
  '/hris/payroll/periods': typeof HrisPayrollPeriodsRoute
  '/hris/payroll/salary-components': typeof HrisPayrollSalaryComponentsRoute
  '/hris/payroll': typeof HrisPayrollIndexRoute
  '/hris/payroll/entries/$id': typeof HrisPayrollEntriesIdRoute
  '/hris/payroll/runs/$id': typeof HrisPayrollRunsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRouteWithChildren
  '/hris': typeof HrisRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/dashboard/$module': typeof DashboardModuleRoute
  '/hris/attendance': typeof HrisAttendanceRoute
  '/hris/compensation': typeof HrisCompensationRoute
  '/hris/compliance': typeof HrisComplianceRoute
  '/hris/core-hr': typeof HrisCoreHrRoute
  '/hris/dashboard': typeof HrisDashboardRoute
  '/hris/disciplinary': typeof HrisDisciplinaryRoute
  '/hris/employees': typeof HrisEmployeesRouteWithChildren
  '/hris/events-meetings': typeof HrisEventsMeetingsRoute
  '/hris/holidays': typeof HrisHolidaysRoute
  '/hris/leaves': typeof HrisLeavesRoute
  '/hris/overtime-approvals': typeof HrisOvertimeApprovalsRoute
  '/hris/overtime-logs': typeof HrisOvertimeLogsRoute
  '/hris/performance': typeof HrisPerformanceRoute
  '/hris/recruitment': typeof HrisRecruitmentRoute
  '/hris/reports': typeof HrisReportsRoute
  '/hris/settings': typeof HrisSettingsRoute
  '/hris/time-management': typeof HrisTimeManagementRoute
  '/hris/timesheets': typeof HrisTimesheetsRoute
  '/hris/training': typeof HrisTrainingRoute
  '/user-management/account': typeof UserManagementAccountRoute
  '/user-management/roles': typeof UserManagementRolesRoute
  '/user-management/users': typeof UserManagementUsersRoute
  '/hris/employees/$id': typeof HrisEmployeesIdRoute
  '/hris/payroll/deductions': typeof HrisPayrollDeductionsRoute
  '/hris/payroll/periods': typeof HrisPayrollPeriodsRoute
  '/hris/payroll/salary-components': typeof HrisPayrollSalaryComponentsRoute
  '/hris/payroll': typeof HrisPayrollIndexRoute
  '/hris/payroll/entries/$id': typeof HrisPayrollEntriesIdRoute
  '/hris/payroll/runs/$id': typeof HrisPayrollRunsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRouteWithChildren
  '/hris': typeof HrisRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/dashboard/$module': typeof DashboardModuleRoute
  '/hris/attendance': typeof HrisAttendanceRoute
  '/hris/compensation': typeof HrisCompensationRoute
  '/hris/compliance': typeof HrisComplianceRoute
  '/hris/core-hr': typeof HrisCoreHrRoute
  '/hris/dashboard': typeof HrisDashboardRoute
  '/hris/disciplinary': typeof HrisDisciplinaryRoute
  '/hris/employees': typeof HrisEmployeesRouteWithChildren
  '/hris/events-meetings': typeof HrisEventsMeetingsRoute
  '/hris/holidays': typeof HrisHolidaysRoute
  '/hris/leaves': typeof HrisLeavesRoute
  '/hris/overtime-approvals': typeof HrisOvertimeApprovalsRoute
  '/hris/overtime-logs': typeof HrisOvertimeLogsRoute
  '/hris/performance': typeof HrisPerformanceRoute
  '/hris/recruitment': typeof HrisRecruitmentRoute
  '/hris/reports': typeof HrisReportsRoute
  '/hris/settings': typeof HrisSettingsRoute
  '/hris/time-management': typeof HrisTimeManagementRoute
  '/hris/timesheets': typeof HrisTimesheetsRoute
  '/hris/training': typeof HrisTrainingRoute
  '/user-management/account': typeof UserManagementAccountRoute
  '/user-management/roles': typeof UserManagementRolesRoute
  '/user-management/users': typeof UserManagementUsersRoute
  '/hris/employees/$id': typeof HrisEmployeesIdRoute
  '/hris/payroll/deductions': typeof HrisPayrollDeductionsRoute
  '/hris/payroll/periods': typeof HrisPayrollPeriodsRoute
  '/hris/payroll/salary-components': typeof HrisPayrollSalaryComponentsRoute
  '/hris/payroll/': typeof HrisPayrollIndexRoute
  '/hris/payroll/entries/$id': typeof HrisPayrollEntriesIdRoute
  '/hris/payroll/runs/$id': typeof HrisPayrollRunsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/dashboard'
    | '/hris'
    | '/login'
    | '/register'
    | '/settings'
    | '/dashboard/$module'
    | '/hris/attendance'
    | '/hris/compensation'
    | '/hris/compliance'
    | '/hris/core-hr'
    | '/hris/dashboard'
    | '/hris/disciplinary'
    | '/hris/employees'
    | '/hris/events-meetings'
    | '/hris/holidays'
    | '/hris/leaves'
    | '/hris/overtime-approvals'
    | '/hris/overtime-logs'
    | '/hris/performance'
    | '/hris/recruitment'
    | '/hris/reports'
    | '/hris/settings'
    | '/hris/time-management'
    | '/hris/timesheets'
    | '/hris/training'
    | '/user-management/account'
    | '/user-management/roles'
    | '/user-management/users'
    | '/hris/employees/$id'
    | '/hris/payroll/deductions'
    | '/hris/payroll/periods'
    | '/hris/payroll/salary-components'
    | '/hris/payroll'
    | '/hris/payroll/entries/$id'
    | '/hris/payroll/runs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/dashboard'
    | '/hris'
    | '/login'
    | '/register'
    | '/settings'
    | '/dashboard/$module'
    | '/hris/attendance'
    | '/hris/compensation'
    | '/hris/compliance'
    | '/hris/core-hr'
    | '/hris/dashboard'
    | '/hris/disciplinary'
    | '/hris/employees'
    | '/hris/events-meetings'
    | '/hris/holidays'
    | '/hris/leaves'
    | '/hris/overtime-approvals'
    | '/hris/overtime-logs'
    | '/hris/performance'
    | '/hris/recruitment'
    | '/hris/reports'
    | '/hris/settings'
    | '/hris/time-management'
    | '/hris/timesheets'
    | '/hris/training'
    | '/user-management/account'
    | '/user-management/roles'
    | '/user-management/users'
    | '/hris/employees/$id'
    | '/hris/payroll/deductions'
    | '/hris/payroll/periods'
    | '/hris/payroll/salary-components'
    | '/hris/payroll'
    | '/hris/payroll/entries/$id'
    | '/hris/payroll/runs/$id'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/dashboard'
    | '/hris'
    | '/login'
    | '/register'
    | '/settings'
    | '/dashboard/$module'
    | '/hris/attendance'
    | '/hris/compensation'
    | '/hris/compliance'
    | '/hris/core-hr'
    | '/hris/dashboard'
    | '/hris/disciplinary'
    | '/hris/employees'
    | '/hris/events-meetings'
    | '/hris/holidays'
    | '/hris/leaves'
    | '/hris/overtime-approvals'
    | '/hris/overtime-logs'
    | '/hris/performance'
    | '/hris/recruitment'
    | '/hris/reports'
    | '/hris/settings'
    | '/hris/time-management'
    | '/hris/timesheets'
    | '/hris/training'
    | '/user-management/account'
    | '/user-management/roles'
    | '/user-management/users'
    | '/hris/employees/$id'
    | '/hris/payroll/deductions'
    | '/hris/payroll/periods'
    | '/hris/payroll/salary-components'
    | '/hris/payroll/'
    | '/hris/payroll/entries/$id'
    | '/hris/payroll/runs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DashboardRoute: typeof DashboardRouteWithChildren
  HrisRoute: typeof HrisRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  UserManagementAccountRoute: typeof UserManagementAccountRoute
  UserManagementRolesRoute: typeof UserManagementRolesRoute
  UserManagementUsersRoute: typeof UserManagementUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hris': {
      id: '/hris'
      path: '/hris'
      fullPath: '/hris'
      preLoaderRoute: typeof HrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/users': {
      id: '/user-management/users'
      path: '/user-management/users'
      fullPath: '/user-management/users'
      preLoaderRoute: typeof UserManagementUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/roles': {
      id: '/user-management/roles'
      path: '/user-management/roles'
      fullPath: '/user-management/roles'
      preLoaderRoute: typeof UserManagementRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/account': {
      id: '/user-management/account'
      path: '/user-management/account'
      fullPath: '/user-management/account'
      preLoaderRoute: typeof UserManagementAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hris/training': {
      id: '/hris/training'
      path: '/training'
      fullPath: '/hris/training'
      preLoaderRoute: typeof HrisTrainingRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/timesheets': {
      id: '/hris/timesheets'
      path: '/timesheets'
      fullPath: '/hris/timesheets'
      preLoaderRoute: typeof HrisTimesheetsRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/time-management': {
      id: '/hris/time-management'
      path: '/time-management'
      fullPath: '/hris/time-management'
      preLoaderRoute: typeof HrisTimeManagementRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/settings': {
      id: '/hris/settings'
      path: '/settings'
      fullPath: '/hris/settings'
      preLoaderRoute: typeof HrisSettingsRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/reports': {
      id: '/hris/reports'
      path: '/reports'
      fullPath: '/hris/reports'
      preLoaderRoute: typeof HrisReportsRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/recruitment': {
      id: '/hris/recruitment'
      path: '/recruitment'
      fullPath: '/hris/recruitment'
      preLoaderRoute: typeof HrisRecruitmentRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/performance': {
      id: '/hris/performance'
      path: '/performance'
      fullPath: '/hris/performance'
      preLoaderRoute: typeof HrisPerformanceRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/overtime-logs': {
      id: '/hris/overtime-logs'
      path: '/overtime-logs'
      fullPath: '/hris/overtime-logs'
      preLoaderRoute: typeof HrisOvertimeLogsRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/overtime-approvals': {
      id: '/hris/overtime-approvals'
      path: '/overtime-approvals'
      fullPath: '/hris/overtime-approvals'
      preLoaderRoute: typeof HrisOvertimeApprovalsRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/leaves': {
      id: '/hris/leaves'
      path: '/leaves'
      fullPath: '/hris/leaves'
      preLoaderRoute: typeof HrisLeavesRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/holidays': {
      id: '/hris/holidays'
      path: '/holidays'
      fullPath: '/hris/holidays'
      preLoaderRoute: typeof HrisHolidaysRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/events-meetings': {
      id: '/hris/events-meetings'
      path: '/events-meetings'
      fullPath: '/hris/events-meetings'
      preLoaderRoute: typeof HrisEventsMeetingsRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/employees': {
      id: '/hris/employees'
      path: '/employees'
      fullPath: '/hris/employees'
      preLoaderRoute: typeof HrisEmployeesRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/disciplinary': {
      id: '/hris/disciplinary'
      path: '/disciplinary'
      fullPath: '/hris/disciplinary'
      preLoaderRoute: typeof HrisDisciplinaryRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/dashboard': {
      id: '/hris/dashboard'
      path: '/dashboard'
      fullPath: '/hris/dashboard'
      preLoaderRoute: typeof HrisDashboardRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/core-hr': {
      id: '/hris/core-hr'
      path: '/core-hr'
      fullPath: '/hris/core-hr'
      preLoaderRoute: typeof HrisCoreHrRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/compliance': {
      id: '/hris/compliance'
      path: '/compliance'
      fullPath: '/hris/compliance'
      preLoaderRoute: typeof HrisComplianceRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/compensation': {
      id: '/hris/compensation'
      path: '/compensation'
      fullPath: '/hris/compensation'
      preLoaderRoute: typeof HrisCompensationRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/attendance': {
      id: '/hris/attendance'
      path: '/attendance'
      fullPath: '/hris/attendance'
      preLoaderRoute: typeof HrisAttendanceRouteImport
      parentRoute: typeof HrisRoute
    }
    '/dashboard/$module': {
      id: '/dashboard/$module'
      path: '/$module'
      fullPath: '/dashboard/$module'
      preLoaderRoute: typeof DashboardModuleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/hris/payroll/': {
      id: '/hris/payroll/'
      path: '/payroll'
      fullPath: '/hris/payroll'
      preLoaderRoute: typeof HrisPayrollIndexRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/payroll/salary-components': {
      id: '/hris/payroll/salary-components'
      path: '/payroll/salary-components'
      fullPath: '/hris/payroll/salary-components'
      preLoaderRoute: typeof HrisPayrollSalaryComponentsRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/payroll/periods': {
      id: '/hris/payroll/periods'
      path: '/payroll/periods'
      fullPath: '/hris/payroll/periods'
      preLoaderRoute: typeof HrisPayrollPeriodsRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/payroll/deductions': {
      id: '/hris/payroll/deductions'
      path: '/payroll/deductions'
      fullPath: '/hris/payroll/deductions'
      preLoaderRoute: typeof HrisPayrollDeductionsRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/employees/$id': {
      id: '/hris/employees/$id'
      path: '/$id'
      fullPath: '/hris/employees/$id'
      preLoaderRoute: typeof HrisEmployeesIdRouteImport
      parentRoute: typeof HrisEmployeesRoute
    }
    '/hris/payroll/runs/$id': {
      id: '/hris/payroll/runs/$id'
      path: '/payroll/runs/$id'
      fullPath: '/hris/payroll/runs/$id'
      preLoaderRoute: typeof HrisPayrollRunsIdRouteImport
      parentRoute: typeof HrisRoute
    }
    '/hris/payroll/entries/$id': {
      id: '/hris/payroll/entries/$id'
      path: '/payroll/entries/$id'
      fullPath: '/hris/payroll/entries/$id'
      preLoaderRoute: typeof HrisPayrollEntriesIdRouteImport
      parentRoute: typeof HrisRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardModuleRoute: typeof DashboardModuleRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardModuleRoute: DashboardModuleRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface HrisEmployeesRouteChildren {
  HrisEmployeesIdRoute: typeof HrisEmployeesIdRoute
}

const HrisEmployeesRouteChildren: HrisEmployeesRouteChildren = {
  HrisEmployeesIdRoute: HrisEmployeesIdRoute,
}

const HrisEmployeesRouteWithChildren = HrisEmployeesRoute._addFileChildren(
  HrisEmployeesRouteChildren,
)

interface HrisRouteChildren {
  HrisAttendanceRoute: typeof HrisAttendanceRoute
  HrisCompensationRoute: typeof HrisCompensationRoute
  HrisComplianceRoute: typeof HrisComplianceRoute
  HrisCoreHrRoute: typeof HrisCoreHrRoute
  HrisDashboardRoute: typeof HrisDashboardRoute
  HrisDisciplinaryRoute: typeof HrisDisciplinaryRoute
  HrisEmployeesRoute: typeof HrisEmployeesRouteWithChildren
  HrisEventsMeetingsRoute: typeof HrisEventsMeetingsRoute
  HrisHolidaysRoute: typeof HrisHolidaysRoute
  HrisLeavesRoute: typeof HrisLeavesRoute
  HrisOvertimeApprovalsRoute: typeof HrisOvertimeApprovalsRoute
  HrisOvertimeLogsRoute: typeof HrisOvertimeLogsRoute
  HrisPerformanceRoute: typeof HrisPerformanceRoute
  HrisRecruitmentRoute: typeof HrisRecruitmentRoute
  HrisReportsRoute: typeof HrisReportsRoute
  HrisSettingsRoute: typeof HrisSettingsRoute
  HrisTimeManagementRoute: typeof HrisTimeManagementRoute
  HrisTimesheetsRoute: typeof HrisTimesheetsRoute
  HrisTrainingRoute: typeof HrisTrainingRoute
  HrisPayrollDeductionsRoute: typeof HrisPayrollDeductionsRoute
  HrisPayrollPeriodsRoute: typeof HrisPayrollPeriodsRoute
  HrisPayrollSalaryComponentsRoute: typeof HrisPayrollSalaryComponentsRoute
  HrisPayrollIndexRoute: typeof HrisPayrollIndexRoute
  HrisPayrollEntriesIdRoute: typeof HrisPayrollEntriesIdRoute
  HrisPayrollRunsIdRoute: typeof HrisPayrollRunsIdRoute
}

const HrisRouteChildren: HrisRouteChildren = {
  HrisAttendanceRoute: HrisAttendanceRoute,
  HrisCompensationRoute: HrisCompensationRoute,
  HrisComplianceRoute: HrisComplianceRoute,
  HrisCoreHrRoute: HrisCoreHrRoute,
  HrisDashboardRoute: HrisDashboardRoute,
  HrisDisciplinaryRoute: HrisDisciplinaryRoute,
  HrisEmployeesRoute: HrisEmployeesRouteWithChildren,
  HrisEventsMeetingsRoute: HrisEventsMeetingsRoute,
  HrisHolidaysRoute: HrisHolidaysRoute,
  HrisLeavesRoute: HrisLeavesRoute,
  HrisOvertimeApprovalsRoute: HrisOvertimeApprovalsRoute,
  HrisOvertimeLogsRoute: HrisOvertimeLogsRoute,
  HrisPerformanceRoute: HrisPerformanceRoute,
  HrisRecruitmentRoute: HrisRecruitmentRoute,
  HrisReportsRoute: HrisReportsRoute,
  HrisSettingsRoute: HrisSettingsRoute,
  HrisTimeManagementRoute: HrisTimeManagementRoute,
  HrisTimesheetsRoute: HrisTimesheetsRoute,
  HrisTrainingRoute: HrisTrainingRoute,
  HrisPayrollDeductionsRoute: HrisPayrollDeductionsRoute,
  HrisPayrollPeriodsRoute: HrisPayrollPeriodsRoute,
  HrisPayrollSalaryComponentsRoute: HrisPayrollSalaryComponentsRoute,
  HrisPayrollIndexRoute: HrisPayrollIndexRoute,
  HrisPayrollEntriesIdRoute: HrisPayrollEntriesIdRoute,
  HrisPayrollRunsIdRoute: HrisPayrollRunsIdRoute,
}

const HrisRouteWithChildren = HrisRoute._addFileChildren(HrisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DashboardRoute: DashboardRouteWithChildren,
  HrisRoute: HrisRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  UserManagementAccountRoute: UserManagementAccountRoute,
  UserManagementRolesRoute: UserManagementRolesRoute,
  UserManagementUsersRoute: UserManagementUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
